---
title: "demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message = FALSE}
library(treeClustDemo)
```

```{r, message = FALSE}
library(plyxp)
xp <- new_plyxp(glinos)
xp <- xp |>
  mutate(
    rows(
      gene = stringr::str_replace(gene_id, "\\.\\d+", ""),
      symbol = AnnotationDbi::mapIds(
        org.Hs.eg.db::org.Hs.eg.db, gene,
        "SYMBOL", "ENSEMBL"
      ),
      symbol = dplyr::case_when(
        is.na(symbol) ~ gene,
        TRUE ~ symbol
      )
    )
  )
head(table(table(rowData(xp)$gene_id)))
```

```{r filter multi-transcript genes}
xp <- xp |>
  group_by(rows(gene_id)) |>
  filter(rows(n() > 1)) |>
  ungroup() |>
  arrange(rows(gene_id))

head(table(table(rowData(xp)$gene_id)))
```


# Computing DESeq2

```{r count split with plyxp}
library(DESeq2)
dds <- xp |>
  mutate(
    train = rbinom(n(), counts, prob = 0.5),
    test = as.integer(counts - train)
  ) |>
  plyxp(
    DESeqDataSet,
    design = ~condition
  )

# estimate sizeFactors on original counts
dds <- plyxp(dds, estimateSizeFactors) |>
  # before computing DESeq, make "counts"
  # into training data
  mutate(
    old_counts = counts,
    counts = train
  ) |>
  # run DESeq2 where counts == train
  plyxp(DESeq)
```

```{r}


## helpers ---

select_common_rows <- function(se, common_rows) {
  new_plyxp(se) |>
    select(rows(all_of(common_names)), everything(), cols(everything())) |>
    se()
}

des_res2rows <- function(se, coef, ...) {
  res <- DESeq2::lfcShrink(se, coef = coef, ...)
  rowData(se)[names(res)] <- res
  se
}
fmt_log <- function(nums, digits = 0) {
  template <- paste0("%s%.", digits, "f")
  sign <- rep("-", length(nums))
  sign[nums > 0] <- "+"
  sprintf(template, sign, abs(nums))
}

#' @param object a dds object that had been predicted
#' @param new_data a different dds object that will take the priors of `object`
#' @param coef string indicating the coef design to use for shrinkage
#' @param type glm type.
#' @export
predict_dds <- function(object, new_data, coef, type = "apeglm") {
  sizeFactors(new_data) <- sizeFactors(object)
  new_data <- estimateDispersionsGeneEst(new_data)
  dispersionFunction(new_data) <- dispersionFunction(object)
  new_data <- estimateDispersionsMAP(new_data) |>
    nbinomWaldTest()

  res <- lfcShrink(object, coef = coef, type = type)
  pc <- attr(res, "priorInfo")$prior.control
  res <- lfcShrink(new_data,
    coef = coef,
    type = type, apeAdapt = FALSE, prior.control = pc
  )
  metadata(new_data)$shrink_results <- res
  new_data
}
```
<!--
## -- main


## using simple_range = sample_range(exons)
##    user  system elapsed
## 217.014   9.442 229.012


## GRangesList
#     user  system elapsed
#  226.947   5.901 234.280


### After optimzation on tree_vctr
#
# # GRangesList
#    user  system elapsed
#  19.331   5.558  25.905
#
# # simple_range
#    user  system elapsed
#   5.664   1.229   7.090
-->

```{r}
system.time({

res <- dds |>
  new_plyxp() |>
  mutate(rows(
    simple_exons = simple_range(exons),
    n_children = 1L
  )) |>
  group_by(rows(gene_id)) |>
  mutate(
    rows(
      n_transcript = n(),
      cut_n_transcript = cut(n_transcript, c(2, 6, 10, Inf),
        include.lowest = FALSE)
    )
  ) |>
  filter(rows(!is.na(cut_n_transcript))) |>
  mutate(
    rows(
      nodes = cluster_data(simple_exons, similarity_method = "basepair") |>
        tree_vctr()
    )
  ) |>
  arrange(rows(nodes))
}) |> print()

# print(res)

```



```{r}
system.time({

xp_inner <- group_by_nodes(res,
  rows(inner_nodes(nodes))
) |>
summarise(
  across(everything(), colSums), rows(n_children = n()),
)
}) |> print()
```


```{r}
res_inner <- plyxp(
  res,
  predict_dds,
  new_data = DESeq2::DESeqDataSet(se(xp_inner),
    design = design(se(res))
  ),
  coef = "condition_WT_vs_KD",
  type = "apeglm"
)
print(res_inner)
```


```{r compute satuRn DTU}
se <- se(xp)
se <- satuRn::fitDTU(se, formula = ~ 0 + condition)
design <- model.matrix(~ 0 + condition, colData(se))
colnames(design)
colnames(design) <- levels(se$condition)
L <- limma::makeContrasts(
  WT_vs_KD = WT - KD,
  levels = design
)

strn <- satuRn::testDTU(
  object = se,
  contrasts = L,
  diagplot1 = FALSE,
  diagplot2 = FALSE
)

```
