---
title: "Glinos 2: Reanalysis"
date: last-modified
---

May require reinstall of treeClustDemo. I found bugs 2026-05-08

```{r}
#| message: false
library(treeClustDemo)
library(plyxp)

se <- readRDS("GTEx_v9_ONT_SummarizedExperiment.rds")
```

```{r}
#| message: false

## Attach exons
txdb_f <- "gencode_v48_txdb.sqlite"
if (!file.exists(txdb_f)) {
  txdb <- txdbmaker::makeTxDbFromGFF("gencode.v48.annotation.gtf.gz")
  AnnotationDbi::saveDb(txdb, file = txdb_f)
} else {
  txdb <- AnnotationDbi::loadDb(txdb_f)
}

exons <- GenomicFeatures::exonsBy(txdb, by = "tx")
txps <- AnnotationDbi::select(
  txdb,
  AnnotationDbi::keys(txdb, "TXID"),
  c("TXNAME", "GENEID"),
  "TXID"
) |>
  tibble::as_tibble() |>
  dplyr::mutate(TXID = as.character(TXID))

stopifnot(
  "txps txid does not match" = match(txps$TXID, names(exons)) |>
    identical(seq_len(length(exons)))
)
```

```{r}
names(exons) <- dplyr::case_when(
  stringr::str_detect(txps$TXNAME, "ENST") ~ txps$TXNAME,
  TRUE ~ paste0(txps$GENEID, "-", stringr::str_sub(txps$TXNAME, 1, 8))
)

slice_indx <- match(rownames(se), txps$TXNAME, nomatch = 0L)
txps <- txps[slice_indx, ]
# txps <- txdb$txps |>
# filter(tx_nms)

se <- se[txps$TXNAME, ]
stopifnot(all.equal(rownames(se), txps$TXNAME))
exons <- exons[slice_indx]
rownames(se) <- names(exons)
rowData(se)$exons <- exons

```

```{r}
xp <- new_plyxp(se)
xp <- xp |>
  filter(
    rows(rowSums(.assays_asis$counts >= 10) >= 6)
  ) |>
  mutate(
    rows(
      gene_id = unlist(gene_id),
      gene = stringr::str_replace(gene_id, "\\.\\d+", ""),
      symbol = AnnotationDbi::mapIds(
        org.Hs.eg.db::org.Hs.eg.db,
        gene,
        "SYMBOL",
        "ENSEMBL"
      ),
      symbol = dplyr::case_when(
        is.na(symbol) ~ gene,
        TRUE ~ symbol
      )
    ),
    cols(
      condition = dplyr::case_when(
        condition == "ctrl" ~ "WT",
        condition == "exp" ~ "KD"
      )
    )
  )
head(table(table(rowData(xp)$gene_id)))
```

```{r}
xp <- xp |>
  group_by(rows(gene_id)) |>
  filter(rows(n() > 1)) |>
  ungroup() |>
  arrange(rows(gene_id))

head(table(table(rowData(xp)$gene_id)))
```

```{r}
#| message: false
library(DESeq2)

set.seed(314)
dds <- xp |>
  mutate(
    counts = round(counts) |> as.integer(),
    train = rbinom(n(), counts, prob = 0.5),
    test = as.integer(counts - train)
  ) |>
  plyxp(
    DESeqDataSet,
    design = ~condition
  )

assay(dds, "avgTxLength") <- NULL

# estimate sizeFactors on original counts
dds <- plyxp(dds, estimateSizeFactors) |>
  # before computing DESeq, make "counts"
  # into training data
  mutate(
    old_counts = counts,
    counts = train
  ) |>
  # run DESeq2 where counts == train
  plyxp(DESeq)

```

```{r}
# extra functions
select_common_rows <- function(se, common_rows) {
  new_plyxp(se) |>
    dplyr::select(
      rows(all_of(common_names)),
      everything(),
      cols(everything())
    ) |>
    ungroup() |>
    se()
}

des_res2rows <- function(se, coef, ...) {
  res <- DESeq2::lfcShrink(se, coef = coef, ...)
  rowData(se)[names(res)] <- res
  se
}
fmt_log <- function(nums, digits = 0) {
  template <- paste0("%s%.", digits, "f")
  sign <- rep("-", length(nums))
  sign[nums > 0] <- "+"
  sprintf(template, sign, abs(nums))
}
```

```{r}
#' @param object a dds object that had been predicted
#' @param new_data a different dds object that will take the priors of `objec`
#' @param coef string indicating the coef design to use for shrinkage
#' @param type glm type.
#' @export
predict_dds <- function(object, new_data, coef, type = "apeglm") {
  if (!is.null(sf <- sizeFactors(object))) {
    sizeFactors(new_data) <- sizeFactors(object)
  }
  new_data <- estimateDispersionsGeneEst(new_data)
  dispersionFunction(new_data) <- dispersionFunction(object)
  new_data <- estimateDispersionsMAP(new_data) |>
    nbinomWaldTest()

  res <- lfcShrink(object, coef = coef, type = type)
  pc <- attr(res, "priorInfo")$prior.control
  res <- lfcShrink(
    new_data,
    coef = coef,
    type = type,
    apeAdapt = FALSE,
    prior.control = pc
  )
  metadata(new_data)$shrink_results <- res
  new_data
}

```

```{r}

system.time({
  res <- dds |>
    new_plyxp() |>
    mutate(rows(
      exon_ranges = ranges(exons),
      n_children = 1L
    )) |>
    group_by(rows(gene_id)) |>
    mutate(
      rows(
        n_transcript = n(),
        cut_n_transcript = cut(
          n_transcript,
          c(2, 6, 10, Inf),
          include.lowest = FALSE
        )
      )
    ) |>
    filter(rows(!is.na(cut_n_transcript))) |>
    mutate(
      rows(
        nodes = cluster_tx_ranges(exon_ranges, similarity_method = "basepair") |>
          tree_vctr()
      )
    ) |>
    arrange(rows(nodes))
}) |>
  print()
res

system.time({
  xp_inner <- group_by_nodes(res, rows(inner_nodes(nodes))) |>
    summarise(
      across(everything(), colSums),
      rows(
        n_children = n(), gene_id = gene_id[1],
        # storing exons
        exons = list(exons)),
    )
}) |>
  print()

res_inner <- plyxp(
  res,
  predict_dds,
  new_data = DESeq2::DESeqDataSet(se(xp_inner), design = design(se(res))),
  coef = "condition_WT_vs_KD",
  type = "apeglm"
)
print(res_inner)

```

```{r}

common_names <- intersect(
  rowData(res_inner) |> names(),
  rowData(res) |> names()
)

# rowRanges(se(res_inner)) <- NULL
.res <- res
rr <- rowRanges(se(res))
rowRanges(se(res)) <- as(rr, "CompressedGRangesList")
# for completeness, and so we can track the source
# of each merge if we are curious later
res <- res |> ungroup() |> mutate(
  rows(
    # converting CompressedGRangesList to a list of
    # CompressedGRangesList
    exons = as.list(exons) |>
      lapply(\(r) relist(r, PartitioningByEnd(length(r))))
  )
)

mcols(rr) <- NULL

inner_desc <- res_inner |> {
  \(se) {
    nodes <- pull(se, rows(nodes))
    # returns all node ids needed to construct
    desc_nodes <- descendants(nodes)
    mapply(
      \(node, wt, trees) {
        treeClustDemo:::new_pure_tree_vctr(
          node = node,
          which_tree = vec_rep(wt, length(node)),
          tree = trees
        )
      },
      node = desc_nodes,
      wt = vctrs::field(nodes, "which_tree"),
      MoreArgs = list(trees = trees(nodes)),
      SIMPLIFY = FALSE
    )
  }
}()

# much faster than doing an lapply
rowRanges(se(res_inner)) <- inner_desc |> {
  \(inner, leaf, rr) {
    lens <- lengths(inner)
    ends <- cumsum(lens)
    unlistData <- vctrs::list_unchop(inner)
    # match inner node desc against observation leaf nodes
    ind <- match(unlistData, leaf)
    # use indices to slice original rowRanges
    rr <- rr[ind]
    # construct CompressedGRangesList
    new(
      "CompressedGRangesList",
      unlistData = rr,
      elementMetadata = rowData(res_inner),
      partitioning = IRanges::PartitioningByEnd(x = ends)
    )
  }
}(leaf = rowData(res)$nodes, rr = rr)

```

```{r}

.se <- rbind(
  select_common_rows(res, common_names),
  select_common_rows(res_inner, common_names)
) |>
  new_plyxp() |>
  ungroup() |>
  mutate(
    rows(.features = as.character(nodes))
  ) |>
  plyxp(des_res2rows, coef = "condition_WT_vs_KD")

```

```{r}
climb_se <- .se |>
  group_by(rows(gene_tree = tree_id(nodes))) |>
  mutate(rows(
    keep_strict = climb(nodes, pvals = pvalue, which = gene_tree[1]),
    keep_ord = climb(nodes, pvals = pvalue, which = gene_tree[1], method = "ord")
  ))
```

```{r}
strict <- climb_se |>
  filter(rows(keep_strict)) |>
  mutate(
    counts = as.integer(test),
    rows(
      train_res = tibble::tibble(
        baseMean, baseVar, log2FoldChange,
        lfcSE, pvalue, padj, condition_WT_vs_KD,
        SE_Intercept, SE_condition_WT_vs_KD )
    )
  ) |>
  dplyr::select(
    counts, old_counts,
    rows(nodes, n_children, gene_id, exons, train_res),
    cols(everything())
  )

strict
```

```{r}

ord <- climb_se |>
  filter(rows(keep_ord)) |>
  mutate(
    counts = as.integer(test),
    rows(
      train_res = tibble::tibble(
        baseMean, baseVar, log2FoldChange,
        lfcSE, pvalue, padj, condition_WT_vs_KD,
        SE_Intercept, SE_condition_WT_vs_KD )
    )
  ) |>
  dplyr::select(
    counts, old_counts,
    rows(nodes, n_children, gene_id, exons, train_res),
    cols(everything())
  )

ord
```

```{r}

dds_strict <- plyxp(strict, DESeq) |>
  plyxp(des_res2rows, coef = "condition_WT_vs_KD")

dds_ord <- plyxp(ord, DESeq) |>
  plyxp(des_res2rows, coef = "condition_WT_vs_KD")

```

```{r}
library(ggplot2)

# p values based on unmerged training data
climb_se |>
  filter(rows(is_leaf(nodes))) |>
  rowData() |>
  tibble::as_tibble() |>
  ggplot(aes(pvalue, fill = n_children > 1)) +
  geom_histogram() +
  labs(title = "Training set, Leaf Nodes")

# p values selected based on merge
plot_data <- dds_strict |>
  rowData() |>
  tibble::as_tibble()

plot_data |>
  ggplot(aes(train_res.pvalue, fill = n_children > 1)) +
  geom_histogram() +
  labs(title = "Training set, Merged")

plot_data |>
  ggplot(aes(pvalue, fill = n_children > 1)) +
  geom_histogram() +
  labs(title = "Test set, Merged")


```

Curious if `padj` has a more uniform distribution:

```{r}
climb_se |>
  filter(rows(is_leaf(nodes))) |>
  rowData() |>
  tibble::as_tibble() |>
  ggplot(aes(padj, fill = n_children > 1)) +
  geom_histogram() +
  labs(title = "Training set, Leaf Nodes - pval adjusted")

plot_data |>
  ggplot(aes(padj, fill = n_children > 1)) +
  geom_histogram() +
  labs(title = "Test set, Merged - pval adjusted")
```

```{r}
plot_data |>
  mutate(node_status = dplyr::case_when(is_leaf(nodes) ~ "leaf", TRUE ~ "inner")) |>
  ggplot(aes(-log10(train_res.pvalue), -log10(pvalue))) +
  geom_point() +
  geom_abline(slope = 1, color = "red") +
  geom_hline(yintercept = -log10(0.00001), linetype = "dotted") +
  geom_vline(xintercept = -log10(0.00001), linetype = "dotted") +
  coord_fixed(ratio = 1, xlim = c(0, 90), ylim = c(0, 90)) +
  facet_grid(cols = vars(node_status))
```

```{r}

multi_sig_trans <- dds_strict |>
  # 'significant' transcripts
  filter(rows(pvalue < 0.00001)) |>
  group_by(rows(gene_id)) |>
  filter(rows(n() > 1, any(n_children > 1))) |>
  mutate(rows(.n = n())) |>
  ungroup() |>
  arrange(rows(dplyr::desc(.n), gene_id)) |>
  mutate(rows(.n = NULL))
  # pull(rows(gene_id))


ord_sig_trans <- dds_ord |>
  # 'significant' transcripts
  filter(rows(pvalue < 0.00001)) |>
  group_by(rows(gene_id)) |>
  filter(rows(n() > 1, any(n_children > 1))) |>
  mutate(rows(.n = n())) |>
  ungroup() |>
  arrange(rows(dplyr::desc(.n), gene_id)) |>
  mutate(rows(.n = NULL))

```

```{r}

format_genomic_pos <- function(
  x,
  # digits = 4,
  suffixes = c("", "KB", "MB", "GB", "TB", "PB")
) {
  scale_pow <- 3L
  x <- as.numeric(x)

  idx <- ifelse(
    is.na(x) | x == 0,
    1L,
    pmin(length(suffixes),
         pmax(1L, floor(log10(abs(x)) / scale_pow) + 1L))
  )

  scaled <- x / (10^(scale_pow * (idx - 1L)))
  # scaled <- signif(scaled, digits = digits)

  out <- format(scaled, trim = TRUE, scientific = FALSE, big.mark = "")
  out <- sub("\\.?0+$", "", out)
  paste0(out, suffixes[idx])
}

plot_explore <- function(se_obj, .gene_id) {

  plot_data <- new_plyxp(se_obj) |>
    filter(rows(gene_id %in% .gene_id, is_leaf(nodes))) |>
    mutate(
      cols(
        col_nodes = hclust(dist(t(.assays_asis$test))) |>
          tree_vctr()
      )
    ) |>
    mutate(
      rows(
        train = .assays$train,
        test = .assays$test,
        col_tree = .cols$col_nodes,
        condition = .cols$condition,
        donor = .cols$donor,
        feature = .features,
        sample = .cols$.samples
      )
    ) |>
    dplyr::select(rows(gene_id, nodes, exons, train:sample)) |>
    rowData() |> tibble::as_tibble()

  hclust_plot <- plot_data$nodes |>
    tree_vctr() |>
    all_nodes() |>
    tree_plot_data()

  # probably should know which direction...
  exon_data <- plot_data |>
    dplyr::select(nodes, exons, feature, gene_id) |>
    mutate(
      nodes = tree_vctr(nodes), #drop other trees
      start = lapply(exons, \(r) start(unlist(r))),
      end = lapply(exons, \(r) end(unlist(r))),
      gstart = vapply(start, min, 1),
      gend = vapply(end, max, 1),
      exons = NULL
    ) |>
    tidyr::unnest(c(start, end)) |>
    dplyr::left_join(dplyr::select(hclust_plot, x, y, nodes), by = "nodes") |>
    mutate(feature = factor(feature, levels = unique(feature))) |>
    group_by(tree = tree_id(nodes)) |>
    mutate(
      min = min(start),
      max = max(end),
      across(
        c(start, end, gstart, gend),
        ~ scales::rescale(.x, from = c(min[1], max[1]), to = c(1.05, 1.95))
      ),
      anno = min(as.integer(feature)) - 0.75
    )

  main_data <- plot_data |>
    dplyr::select(-c(exons, feature)) |>
    tidyr::unnest(-nodes) |>
    mutate(nodes = tree_vctr(nodes)) |>
    dplyr::left_join(dplyr::select(exon_data, feature, nodes) |> dplyr::distinct(), by = "nodes") |>
    dplyr::arrange(col_tree) |>
    dplyr::mutate(sample = factor(sample, unique(sample)))

  .hclust_data <- hclust_plot |>
    mutate(
      min_y = min(dplyr::c_across(starts_with("y")), na.rm = TRUE),
      max_y = max(dplyr::c_across(starts_with("y")), na.rm = TRUE),
      across(starts_with("y"), ~ scales::rescale(.x, to = c(0.95, 0.05), c(min_y[1], max_y[1]))),
      tree = tree_id(nodes)
    ) |>
    dplyr::left_join(dplyr::distinct(exon_data, tree, gene_id),
      by = "tree") |>
    tibble::as_tibble()

    ## we shouldnt use dds_strict here...
  .node_data <- dds_strict |>
    ungroup() |>
    # 'significant' transcripts
    filter(rows(gene_id %in% .gene_id)) |>
    dplyr::select(rows(nodes, pvalue)) |>
    rowData() |> tibble::as_tibble() |>
    dplyr::left_join(.hclust_data, by = "nodes")

     # scale_ysidex_continuous(
     #   labels = \(x) {
     #     if (any(grepl("^6", x = x))) {
     #       # browser()
     #       nums <- as.numeric(x)
     #       hist_labs <- nums < 6304e4
     #       x[hist_labs] <- scales::rescale(nums[hist_labs], to = c(6100, 0), from = 6300.7e4 + c(0, 3e4)) |> round() |> as.character()
     #     }
     #     x
     #   }, breaks = c(6300.7e4 + (0:3 * 1e4), 6304e4 + (0:3 * 1e4))
     # ) +

  anno_data <- exon_data |>
    dplyr::reframe(
      breaks = scales::breaks_extended()(c(min[1], max[1]), n = 5),
      min = min[1],
      max = max[1],
      y = anno[1],
      x = scales::rescale(breaks, from = c(min, max), to = c(1.05, 1.95)),
      gene_id = gene_id[1]
    ) |>
    filter(dplyr::between(breaks, min, max))

  .hm <- ggplot(main_data, aes(x = sample, y = feature)) +
    geom_tile(aes(fill = log10(test + 1))) +
    geom_xsidetile(aes(y = "condition", xfill = condition)) +
    geom_xsidetile(aes(y = "donor", xfill = donor)) +
    geom_ysidesegment(aes(x = gstart, xend = gend), data = exon_data) +
    facet_grid(rows = vars(gene_id), scales = "free_y", space = "free_y") +
    ggside(y.pos = "left", respect_side_labels = "y", collapse = "x") +
    theme_minimal() +
    theme(
      ggside.panel.scale.y = 3, panel.grid = element_blank(),
      ggside.panel.grid = element_blank(), legend.position = "top", ggside.axis.ticks.y = element_line(), legend.title = element_text(vjust = .5),
      axis.text.x = element_blank(), axis.ticks.x = element_blank())

  .hm <- .hm +  geom_ysiderect(aes(y = feature, height = 0.75, ysidexmin = start, ysidexmax = end), fill = "steelblue", data = exon_data, inherit.aes = FALSE) +
    # scale_ysidex_continuous() +
    geom_ysidepoint(aes(x = y, y = x), data = .hclust_data,  color = "grey"
    ) +
    geom_ysidesegment(aes(y = x, x = y, xend = y_end),
      data = subset(.hclust_data, !is.na(y_end)), color = "grey") +
    geom_ysidesegment(aes(y = x_start, x = y, yend = x_end),
      data = subset(.hclust_data, !is.na(x_end)), color = "grey") +
    scale_fill_viridis_c()

  .hm <- .hm +
    geom_ysidepoint(aes(y = x, x = y, ycolor = -log10(pvalue)), data = .node_data) +
    scale_y_discrete(labels = \(x) ifelse(grepl("^ENST", x = x), "", x), expand = expansion(add = c(2, 0))) +
    scale_x_discrete(labels = \(x)ifelse(grepl("^GTEX", x = x), "", x)) +
    scale_color_viridis_c(option = "C", aesthetics = "ycolour", guide = guide_colorbar(available_aes = "ycolour"))

  .hm <- .hm +

    guides(
      fill = guide_colourbar(order = 4, theme = theme(legend.title = element_text(vjust = .8))),
      ycolour = guide_colourbar(available_aes = "ycolour", order = 1, theme = theme(legend.title = element_text(vjust = .8)))) +
    scale_fill_brewer(aesthetics = c("xfill"), palette = "Paired") +
    labs(y = "Transcript",
      x = sprintf("Cluster Height%sGenomic Position%sSample",
        paste(rep(" ", 50), collapse = ""), paste(rep(" ", 60), collapse = "")),
      xfill = "Sample ID")


  .hm + geom_ysidepath(data = group_by(anno_data, gene_id) |> dplyr::reframe(x = c(1.05, 1.96), y = .25), aes(x = x, y = y)) + geom_ysidetext(data = anno_data, aes(x = x, y = -.25, label = format_genomic_pos(breaks)), angle = 15, hjust = 1, size = 2) + coord_cartesian(clip = 'off')

}


for (i in 0:5) {
  png(sprintf("plot%i.png",i), width = 9, height = 15, res = 100, unit = "in")
  plot_explore(climb_se, multi_sig_trans |> pull(rows(gene_id)) |> unique() |> _[(i * 3) + (1:3)]) |> plot()
  dev.off()
}
```

```{r}

.se_data <- climb_se |>
  ungroup() |>
  filter(rows(
    gene_id == rowData(multi_sig_trans)$gene_id[1],
    is_leaf(nodes))) |>
  mutate(cols(
    col_nodes = hclust(dist(t(.assays_asis$test))) |> tree_vctr()
  ))



plot_data <- .se_data |>
  mutate(
    rows(
      train = .assays$train,
      test = .assays$test,
      col_tree = .cols$col_nodes,
      condition = .cols$condition,
      donor = .cols$donor,
      feature = .features,
      sample = .cols$.samples
    )
  ) |>
  dplyr::select(rows(nodes, exons, train:sample)) |>
  rowData() |> tibble::as_tibble()


hclust_plot <- tree_plot_data(all_nodes(tree_vctr(plot_data$nodes)))

exon_data <- plot_data |>
  dplyr::select(nodes, exons, feature) |>
  mutate(
    nodes = tree_vctr(nodes), #drop other trees
    start = lapply(exons, \(r) start(unlist(r))),
    end = lapply(exons, \(r) end(unlist(r))),
    gstart = vapply(start, min, 1),
    gend = vapply(end, max, 1),
    exons = NULL
  ) |>
  tidyr::unnest(c(start, end)) |>
  # dplyr::left_join(hclust_plot, by = "nodes") |>
  mutate(feature = factor(feature, levels = unique(feature)))

# ggplot(exon_data, aes(feature)) +
#   geom_segment(aes(y = gstart, yend = gend)) +
#   geom_rect(aes(width = 0.75, ymin = start, ymax = end), fill = "steelblue")
```

```{r}

```

```{r}
library(ggside)
main_data <- plot_data |>
  dplyr::select(-c(exons, feature)) |>
  tidyr::unnest(-nodes) |>
  mutate(nodes = tree_vctr(nodes)) |>
  dplyr::left_join(dplyr::select(exon_data, feature, nodes) |> dplyr::distinct(), by = "nodes") |>
  dplyr::arrange(col_tree) |>
  dplyr::mutate(sample = factor(sample, unique(sample)))

.hclust_data <- hclust_plot |>
  mutate(
    across(starts_with("y"), ~ scales::rescale(.x, c(0, 3e4), c(6100, 0)) + 6300.7e4)
  )
.node_data <- dds_strict |>
  ungroup() |>
  # 'significant' transcripts
  filter(rows(gene_id == rowData(multi_sig_trans)$gene_id[1])) |>
  dplyr::select(rows(nodes, pvalue)) |>
  rowData() |> tibble::as_tibble() |>
  dplyr::left_join(.hclust_data, by = "nodes")

hm <- ggplot(main_data, aes(x = sample, y = feature)) +
  geom_tile(aes(fill = log10(test + 1))) +
  geom_xsidetile(aes(y = "condition", xfill = condition)) +
  geom_xsidetile(aes(y = "donor", xfill = donor)) +
  geom_ysidesegment(aes(x = gstart, xend = gend), data = exon_data) +
  geom_ysiderect(aes(y = feature, height = 0.75, ysidexmin = start, ysidexmax = end), fill = "steelblue", data = exon_data, inherit.aes = FALSE) +
  geom_ysidepoint(aes(x = y, y = x), data = .hclust_data, color = "grey") +
  geom_ysidesegment(aes(y = x, x = y, xend = y_end),
    data = subset(.hclust_data, !is.na(y_end)), color = "grey") +
  geom_ysidesegment(aes(y = x_start, x = y, yend = x_end),
    data = subset(.hclust_data, !is.na(x_end)), color = "grey") +
  scale_fill_viridis_c() +
  geom_ysidepoint(aes(y = x, x = y, ycolor = -log10(pvalue)), data = .node_data) +
  theme_minimal() +
  scale_y_discrete(labels = \(x) ifelse(grepl("^ENST", x = x), "", x)) +
  scale_x_discrete(labels = \(x)ifelse(grepl("^GTEX", x = x), "", x)) +
  scale_color_viridis_c(option = "C", aesthetics = "ycolour", guide = guide_colorbar(available_aes = "ycolour")) +
  scale_ysidex_continuous(
    labels = \(x) {
      if (any(grepl("^6", x = x))) {
        # browser()
        nums <- as.numeric(x)
        hist_labs <- nums < 6304e4
        x[hist_labs] <- scales::rescale(nums[hist_labs], to = c(6100, 0), from = 6300.7e4 + c(0, 3e4)) |> round() |> as.character()
      }
      x
    }, breaks = c(6300.7e4 + (0:3 * 1e4), 6304e4 + (0:3 * 1e4))
  ) +
  theme(
    ggside.panel.scale.y = 3, panel.grid = element_blank(),
    ggside.panel.grid = element_blank(), legend.position = "top", ggside.axis.ticks = element_line(), legend.title = element_text(vjust = .5)) +
  guides(
    x = guide_axis(angle = 45),
    fill = guide_colourbar(order = 4, theme = theme(legend.title = element_text(vjust = .8))),
    ycolour = guide_colourbar(available_aes = "ycolour", order = 1, theme = theme(legend.title = element_text(vjust = .8)))) +
  scale_fill_brewer(aesthetics = c("xfill"), palette = "Paired") +
  labs(y = "Transcript",
    x = sprintf("Cluster Height%sGenomic Position%sSample",
      paste(rep(" ", 50), collapse = ""), paste(rep(" ", 60), collapse = "")),
    xfill = "Sample ID") +
  ggside(y.pos = "left", respect_side_labels = "y")
hm

ggplot2::ggsave(filename = "Example_Climb_Res.png", plot = hm, width = 7, height = 6, units = "in")

```

```{r}
.sig <- dds_strict |>
  #arbitrary contrary
  filter(rows(pvalue < 0.00001))
.sig
.sig_arranged <- .sig |>
  arrange(rows(pvalue, dplyr::desc(n_children))) |>
  dplyr::select(
    counts,
    rows(pvalue)
  )
.sig_arranged

rowRanges(se(.sig_arranged))

```
